apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: user-role-update-template
  title: User Role Update Template
  description: A template for updating existing Backstage user roles and group memberships
  tags:
    - user
    - role
    - update
    - catalog
    - backstage
spec:
  type: user
  rules:
    - allow: [catalog.location.create]
  parameters:
    - title: User Information
      required:
        - user
        - repoUrl
      properties:
        user:
          title: User
          type: string
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind: User
        repoUrl:
          title: Repository Location
          type: string
          default: github.com?repo=backstage-catalog&owner=Devweave
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
            allowedOwners:
              - Devweave
          description: Repository where the user catalog files are stored

    - title: Role Update
      required:
        - newMemberOf
      properties:
        newMemberOf:
          title: New Group Membership
          type: string
          description: The new group this user should belong to
          enum:
            - group:default/guests
            - group:default/admins
            - group:default/developers
            - group:default/clients
          enumNames:
            - 'Guests'
            - 'Administrators'
            - 'Developers'
            - 'Clients'
          ui:help: 'Select the new group for this user'
        updateReason:
          title: Update Reason
          type: string
          description: Reason for the role update (optional)
          ui:widget: textarea
          ui:help: 'Provide a brief reason for this role change'

  steps:
    - id: fetch-repo
      name: Fetch Repository
      action: fetch:plain
      input:
        url: https://github.com/${{ (parameters.repoUrl | parseRepoUrl).owner }}/${{ (parameters.repoUrl | parseRepoUrl).repo }}
        targetPath: ./

    - id: update-user-role
      name: Update User Role
      action: roadiehq:utils:fs:replace
      input:
        files:
          - file: ./users/${{ (parameters.user | parseEntityRef).name }}.yaml
            find: 'memberOf: \[.*\]'
            replaceWith: 'memberOf: [${{ parameters.newMemberOf }}]'
            matchRegex: true

    - id: publish
      name: Publish
      action: publish:github:push
      input:
        repoUrl: ${{ parameters.repoUrl }}
        branchName: master
        commitMessage: 'Update user role for ${{ (parameters.user | parseEntityRef).name }}'
        gitAuthorName: 'Backstage Scaffolder'
        gitAuthorEmail: 'scaffolder@backstage.io'
    
    - id: fetch
      name: Fetch catalog entity
      action: catalog:fetch
      input:
        entityRef: ${{ parameters.user }}

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Updated User File
        url: ${{ steps.publish.output.remoteUrl }}/blob/master/users/${{ (parameters.user | parseEntityRef).name }}.yaml
