package_rename_config:
  android:
    app_name: "${{ values.appName }}" # (String) The display name of the android app
    package_name: "${{ values.packageName }}" # (String) The package name of the android app
    override_old_package: # (Optional) (String) Use this to delete the old folder structure of MainActivity or to use the existing code with the new package name
    lang: kotlin # (Optional) (String) The android development language {kotlin(default) or java}

  ios:
    app_name: "${{ values.appName }}" # (String) The display name of the ios app
    bundle_name: "${{ values.appName }}" # (String) The bundle name of the ios app
    package_name: "${{ values.packageName }}" # (String) The product bundle identifier of the ios app

  linux:
    app_name: "${{ values.appName }}" # (String) The window title of the linux app
    package_name: "${{ values.packageName }}" # (String) The application id of the linux app
    exe_name: "${{ values.repoName }}" # (String) The executable name (binary name) of the linux app

  macos:
    app_name: "${{ values.appName }}" # (String) The product name of the macos app
    package_name: "${{ values.packageName }}" # (String) The product bundle identifier of the macos app
    copyright_notice: "Copyright © {% now 'utc', '%Y' %} Devweave. All rights reserved." # (String) The product copyright of the macos app

  web:
    app_name: "${{ values.appName }}" # (String) The title of the web app and PWA
    short_app_name: "${{ values.appName }}" # (String) The short display name of the PWA (Optional, defaults to app_name if not set)
    description: "Flutter application - ${{ values.appName }}" # (String) The description of the web app and PWA

  windows:
    app_name: "${{ values.appName }}" # (String) The window title & software name of the windows app
    organization: "Devweave" # (String) The organization name (company name) of the windows app
    copyright_notice: "Copyright © {% now 'utc', '%Y' %} Devweave. All rights reserved." # (String) The legal copyright of the windows app
    exe_name: "${{ values.repoName }}" # (String) The executable name (binary name) of the windows app